### ISSUE TITLE
Fulfill the open-source checklist

### ISSUE THREAD

**Issue by igaray** [inaka/katana-test#2]
## General Items
- [x] It has a github repo
- [x] It has a proper Apache2 LICENSE file
- [x] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [x] It's tested
- [x] It's hooked to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT)
- [x] It has a link to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT) in its README
- [x] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page
## For Libraries
- [ ] It provides a sample application
- [ ] Examples of use are documented in the README or linked from there
- [x] It's checked with [Gadget](http://gadget.inakalabs.com)
- [ ] It's shared on [Erlang Central](http://erlangcentral.org/add-news/)
- [ ] It's published on [Hex.pm](https://hex.pm)
